#!/usr/bin/env perl

# blows up if we use strict before this, damn source filter
use Perl6::Perldoc::Parser;
use Perl6::Perldoc::To::Text;

use strict;
use warnings;
use Getopt::Long qw(:config auto_help);
use Pod::Usage;

our $VERSION = '0.01';

GetOptions(
   'F|file=s' => \my $from_file,
) or pod2usage();

if (!$from_file) {
    die "Only -F is supported for now\n";
}

print Perl6::Perldoc::Parser->parse($from_file, {all_pod=>'auto'})
                            ->report_errors()
                            ->to_text();

