=begin pod

=head1 NAME

grok - Read Perl 6 documentation

=head1 SYNOPSIS

B<grok> <options>

 Options:
   -F FILE, --file=FILE     Read documentation from the supplied file

=head1 AUTHOR

Hinrik E<Ouml>rn SigurE<eth>sson, hinrik.sig@gmail.com

=head1 LICENSE AND COPYRIGHT

Copyright 2009 Hinrik E<Ouml>rn SigurE<eth>sson

Grok is distributed under the terms of the Artistic License 2.0.
For more details, see the full text of the license in the file F<LICENSE>
that came with this distribution.

=comment vim: filetype=perl6

=end pod
