=begin pod

=NAME
grok - Perl 6 documentation reader

=begin SYNOPSIS
K<grok <options>>

 Options:
   -F FILE, --file=FILE     Read documentation from the supplied file
=end SYNOPSIS

=head1 Prior art and inspiration

=item L<Perl 5's K<perldoc>|http://perldoc.perl.org/perldoc.html>
=item L<Python's K<pydoc>|http://docs.python.org/library/pydoc.html>
=item L<Ruby's K<ri>|http://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/lib/rdoc/>
=item L<http://svn.pugscode.org/pugs/ext/Perldoc/>
=item L<http://svn.pugscode.org/pugs/examples/perldoc.pl>

=begin WARNING
=head2 Bugs in C<Perl6::Perldoc>

Long lines are not wrapped to fit your terminal. Whitespace in paragraphs is
preserved, counter to the spec.

Formatting codes using french quotes (C<C«»>) aren't parsed correctly, so they
are rendered verbatim.
=end WARNING

=AUTHOR
Hinrik Örn Sigurðsson, L<hinrik.sig@gmail.com>

=begin LICENSE
Copyright 2009 Hinrik Örn Sigurðsson

K<grok> is distributed under the terms of the Artistic License 2.0.
For more details, see the full text of the license in the file L<LICENSE>
that came with this distribution.
=end LICENSE

=comment vim: filetype=perl6

=end pod
