use strict;
use warnings;
use Test::More tests => 4;
use Test::Script;
use Pod::Simple ();
use Pod::Text ();
use Pod::Xhtml ();
diag('Pod::Parser version ' . $Pod::Parser::VERSION);
diag('Pod::Simple version ' . $Pod::Simple::VERSION);
diag('Pod::Text version '   . $Pod::Text::VERSION);
diag('Pod::Xhtml version '  . $Pod::Xhtml::VERSION);
use_ok('App::Grok');
use_ok('App::Grok::Parser::Pod5');
use_ok('App::Grok::Parser::Pod6');
script_compiles_ok('script/grok', 'grok compiles');
